baseURL = "https://www.lukemperez.com"
languageCode = "en-us"
title = "Luke M. Perez"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 4 # Set the number of posts to show before overflowing to the next page.
summaryLength = 50 # Configure how long the post summary should be on the homepage.

# Add your Google Analytics identifier: UA-XXXXXXXX-X
googleAnalytics = ""

# Add your Disqus shortname here.
disqusShortname = ""

[taxonomies]
  tag = "tags"

[author]
	name = "Luke M. Perez, Ph.D."

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = true

[params]
	math = true
	# Blog description at the top of the homepage. Supports markdown.
	description = "Personal site with links to my (infrequent) blogging and academic scholarship."

    showReadMore = true

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

	# Add links to your accounts. Remove the ones you don't want to include.
	# Main
	email = "<mailto:lukemerez@gmail.com>"
    # facebook = "#"
    twitter = "https://www.twitter.com/lukemperez"
	instagram = "https://www.instagram.com/lukemperez"
	# tumblr = "#"
	# reddit = "#"
	# pinterest = "#"
	# youtube = "#"
  #   vimeo = "#"
	# weibo = "#"
	# vk = "#"
	# linkedin = "#"

	# # Writing
  #   medium = "#"
	# blogger = "#"
	# wordpress = "#"
  #
	# # Creative & Visual
  #   dribbble = "#"
	# behance = "#"
	# deviantart = "#"
	# flickr = "#"
  #
  #   # Audio & Music
  #   soundcloud = "#"
  #
	# # Programming
    github = "https://www.github.com/lukemperez"
	# stackoverflow = "#"
	# gitlab = "#"
	# codepen = "#"
  #
  #   # Academic
  #   googlescholar = "#"
  #   impactstory = "#"
  #   orcid = "#"
#
# Menu links along the sidebar navigation.
[[menu.main]]
	identifier = "about"
	name = "About"
	url = "/about/"
	weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
  identifier = "Publications"
  name = "Publications"
  url = "/publications/"
  weight = 2
#
# [[menu.main]]
# 	identifier = "tags"
# 	name = "Tags"
# 	url = "/tags/"
# 	weight = 2
#
# [[menu.main]]
# 	name = "Archives"
# 	identifier = "archives"
# 	url = "/archives/"
# 	weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = true

###
#
# baseurl = "https://www.lukemperez.com/" # -- Sept 8, 2020 troubleshoot
# # baseurl = "lukemperez.github.io/lukemperez"
# title = "Luke M Perez"
# canonifyurls = true
# relativeurls = false
# paginate = 10
# theme = "noteworthy"
# # theme = "even"
# DisqusShortname = ""
# googleAnalytics = "UA-97407722-1"
# ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
# pluralizeListTitles = false
# buildFuture = true
#
# [params]
#
# # Date format (refer to Go's date format: http://flippinggodateformat.com)
# date_format = "2 January 2006"
#
# # Number of posts to show on main page.
# posts_count = 3
#
# # Number of publications to show on main page.
# pubs_count = 2
#
# # Number of posts to show on main page.
# seminars_count = 2
#
# # options for highlight.js (version, additional languages, and theme)
#   highlightjsVersion = "9.11.0"
#   highlightjsCDN = "//cdn.bootcss.com"
#   highlightjsLang = ["r", "yaml"]
#   highlightjsTheme = "github"
#
# [[params.social]]
#   icon = "university"
#   icon_pack = "fa"
#   link = "https://www.scetl.asu.edu"
#   text = "School of Civic and Economic Thought and Leadership, Arizona State University."
#
# [[params.social]]
#   icon = "envelope"
#   icon_pack = "fa"
#   link = "mailto:lukemperez@asu.edu"
#   text = "lukemperez@asu.edu"
#
# [[params.social]]
#   icon = "twitter"
#   icon_pack = "fa"
#   link = "https://twitter.com/lukemperez"
#   text = "@lukemperez"
#   site = "Twitter"
#
# [[params.social]]
#   icon = "github-alt"
#   icon_pack = "fa"
#   link = "https://github.com/lukemperez/"
#   text = "lukemperez"
#   site = "GitHub"
#
# # [[params.social]]
# #   icon = "google-scholar"
# #   icon_pack = "ai"
# #   link = "https://scholar.google.com/citations?user=vamErfkAAAAJ"
# #   text = "Google Scholar"
#
# # Navigation Links
# # The weight parameter defines the order that the links will appear in.
#
# [[menu.main]]
#   name = "Notes"
#   url = "/notes/"
#   weight = 1
#
# [[menu.main]]
#   name = "Publications"
#   url = "/publications/"
#   weight = 2
#
# [[menu.main]]
#   name = "Teaching"
#   url = "/teaching/"
#   weight = 3
#
# [[menu.main]]
#   name = "Talks"
#   url = "/talks/"
#   weight = 4
#
# [[menu.main]]
#   name = "About"
#   url = "/#about/"
#   weight = 5

# [outputFormats]
#   [outputFormats.PlainTextFile]
#   baseName = "keybase"
#   isPlainText = true
#   mediaType = "text/plain"
#   isHTML = false
