# hostname (and path) to the root eg. http://spf13.com/
baseurl = "https://www.lukemperez.com"
title = "Luke Matthew Perez"
copyright = "&copy; 20017 lukemperez"
enableEmoji = true
footnotereturnlinkcontents = "<sup>^</sup>"

DefaultContentLanguage = "en"

showRightSidebar = true

# If you want all of the languages to be put below their
# respective language code, enable DefaultContentLanguageInSubdir = true.
# Without enabling it english content will be in the root and other languages
# in their respective subfolder such as /sv/.
# See [Languages] settings at the end of this file.

# Language
languageCode = "en"

# SES friendly url:s
canonifyurls = true

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = "UA-97407722-1"

# Metadata format
# "yaml", "toml", "json"
metaDataFormat = "yaml"

# Theme to use (located in /themes/THEMENAME/)
theme = "hugo-bootstrap-premium"

# Pagination
paginate = 10
paginatePath = "page"

# Enable Disqus integration
disqusShortname = ""

[permalinks]
    post = "/:year/:month/:day/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
    category = "categories"

[author]
    name = "yourname"
    email = "yourname@example.com"

#
# All parameters below here are optional and can be mixed and matched.
#

# bootswatch theme name, unmark and select one: cerulean, cosmo, cyborg, darkly,
# default, flatly, journal,  lumen, paper, readable, sandstone, simplex,
# slate, spacelab, superhero, united, yeti.

[params.theme]
  name = "simplex"

# [params.popover]
#   # This is a highly configurable popover form.
#   enablepopover = false #enable or disable popover: true/false.
#   posturl = "https://zapier.com/hooks/..."
#   headerimage = "//placehold.it/1000x600"
#   expirecookie = 5 #show it again after number of days to visitor that has not subscribed.
#   cookiename = "mycookie1" #give the cookie a unique name variable (avoid spaces and strange characters).
#   signupheader = "Join Our Newsletter"
#   showmodaltimeout = 10000 #show popover modal after time interval in milliseconds.
#   mouseleave = true #show popover when mouse leaves window: true/false.
#   modalsize = "" #lg or sm. Empty is md. If phone is detected lg is used.
#   imagedescription = "Placeholder image for this popover modal optin form"
#   signuptext = "Signup today for free and be the first to get notified on new updates."
#   inputplaceholder = "Enter your email"
#   submitbutton = "Subscribe"
#   successmessage = "Thanks for your subscription!"
#   errormessage = "Submitting form failed!"
#   optin = true #opt-in: true/false

[params]
    # menu for changing language. This changes languages with js and stores the choice with the help
    # of JavaScript in a Cookie. Then the path is rewritten with pathnamereplace.js. The name of the
    # md files needs to have the same name for each language abbreviation to work correctly. Example:
    # showcase.en.md and showcase.sv.md. It only works if DefaultContentLanguageInSubdir = true
    switchlang = false

    # You can use markdown here.
    # BrandImage = "" #top header brand image. urls permited:
    brand = "" # brand image alt text.
    topline = "Your friendly neighborhood grand strategist"
    footline = "code with <i class='fa fa-heart'></i>"

    # Show a sidebar menu
    showRightSidebar = false

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Home".
    home = "home"

    mailmunchid = "" # Mailmunch site id
    sumomeid = "" # Sumome id

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "default"

    # Sidebar social links.
    github = "lukemperez" # Your Github profile ID
    bitbucket = "" # Your Bitbucket profile ID
    linkedin = "lukemperez" # Your LinkedIn profile ID (from public URL)
    googleplus = "" # Your Google+ profile ID
    facebook = "" # Your Facebook profile ID
    twitter = "lukemperez" # Your Twitter profile ID
    youtube = ""  # Your Youtube channel ID
    flattr = ""  # populate with your flattr uid

    # Enable Keybase in Contact section by entering your keybase.io username.
    keybase = ""

    # Date format (refer to Go's date format: http://flippinggodateformat.com )
    #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
    date_format = "Mon, 2 Jan 2006"

    # Enable LaTeX math rendering
    # If 'false', you can enable it on a per-page basis
    math = true

[blackfriday]
    angledQuotes = true
    fractions = false
    hrefTargetBlank = false
    latexDashes = true
    plainIdAnchors = true
    extensions = []
    extensionmask = []

    # Menus
    # If you want active menu items highlighted for internal pages don't add them here, they need to be added in each files front matter.
    # like this:
    [menu]
        [[menu.main]]
        name = "Home"
        url = "/about"
        weight = 1

        [[menu.main]]
        name = "posts"
        url = "#publications"
        weight = 2

        [[menu.main]]
        name = "Publications"
        url = "#/publications"
        weight = 3

        [[menu.main]]
        name = "Projects"
        url = "#/projects"
        weight = 4

        [[menu.main]]
        name = "Teaching"
        url = "#teaching"
        weight = 5

    #     [menu.main]
    #        name = "Showcase"
    #        weight = 3
    #        identifier = "showcase"
    # i18n menus. A menu will be added for each language to the right in the top menu. This menu will switch to the selected language. Remember to add the corresponding language in pathnamereplace.js.
    #[[Languages.sv.menu.switchlang]]
    #  name = "English"
    #  identifier = ""
    #  weight = 4
    #  url = "en"

    # [Languages]
    # [Languages.en]
    # weight = 1
    # # copyright = "(c) 2016 Copyright my blog"
    # # title = "My blog" # Site title
    # [[Languages.en.menu.main]]
    # name = "Luke M Perez"
    # pre = ""
    # weight = 2
    # identifier = "post"
    # url = "/post/"

    # [[Languages.en.menu.main]]
    # name = "About"
    # weight = 1
    # identifier = ""
    # url = "/about"
    # pre = "<i class='fa fa-road'></i>"

    # [[Languages.en.menu.main]]
    # name = "Dashboard"
    # identifier = ""
    # weight = 3
    # url = "https://appernetic.io/app/"
    #
    # [[Languages.en.menu.footer]] # add  links to the bottom right corner.
    # name = "Disclaimer"
    # pre = "<i>&middot;</i>"
    # identifier = "disclaimer"
    # weight = 1
    # url = "/disclaimer/"
    #
    # [[Languages.en.menu.footer]]
    # name = "Terms"
    # identifier = "terms"
    # weight = 2
    # url = "/terms/"

    # [Languages.sv]
    # weight = 2
    # title = "Min blog" # Site title
    # copyright = "(c) 2016 Alla rättigheter"
    #
    # [[Languages.sv.menu.main]]
    # name = "Bloggen"
    # pre = ""
    # weight = 2
    # identifier = "post"
    # url = "/sv/post/"

    # [[Languages.sv.menu.footer]] # add  links to the bottom right corner.
    # name = "Ansvarsfriskrivning"
    # pre = "<i>&middot;</i>"
    # identifier = "friskrivning"
    # weight = 1
    # url = "/sv/friskrivning/"
    #
    # [[Languages.sv.menu.footer]]
    # name = "Vilkor"
    # identifier = "vilkor"
    # weight = 2
    # url = "/sv/vilkor/"
    #
    #
    # [Languages.sv.taxonomies]
    # tag = "Taggar"
    # topic = "Ämne"
