baseurl = "http://lukemperez.com/"
languageCode = "en-us"
title = "Luke M Perez"
copyright = "2016 Luke M Perez"
address = "Austin, TX"
publishdir = "public"
canonifyurls = "true"

# basic parameters 
[params]
    name = "Luke M Perez"
    role = "Doctoral Student"
    organization = "University of Texas at Austin"
    interests = ["International Relations", "National Security", "Just War", "Religion", "Political Philosophy"]
    qualifications = ["Research Design", "Qualitative Research Methods", "International Relations Theory", "Greek & Latin"]
    email = "lukemperez@utexas.edu"

    date_format = "Mon, Jan 2, 2006"

    # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
    math = false

    # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
    custom_css = []
    custom_js  = []

	[[params.education]]
		course = "PhD in Government"
		institution = "University of Texas at Austin"
		year = "in-progress"
	[[params.education]]
		course = "MA in Political Science"
		institution = "Villanova University"
		year = "2011"

	[[params.education]]
		course = "BA in Greek and Latin, Political Science"
		institution = "The Ohio State University"
		year = "2007"

	# Social Media  
	[[params.social]]
		icon = "github"
		icon_pack = "fa"
		link = "//github.com/lukemperez"

	[[params.social]]
		icon = "twitter"
		icon_pack = "fa"
		link = "//twitter.com/lukemperez"

# Navigation Links  
# 
# Weight parameters determine order of appearance for links

[[menu.main]]
	name = "Home"
	url = "#"
	weight = 1

[[menu.main]]
	name = "Publications"
	url = "#publications"
	weight = 2

[[menu.main]]
	name = "Posts"
	url = "#posts"
	weight = 3

[[menu.main]]
	name = "Projects"
	url = "#projects"
	weight = 4

[[menu.main]]
	name = "Teaching"
	url = "#teaching"
	weight = 5

[[menu.main]]
	name = "Contact"
	url = "#contact"
	weight = 6
